name: GitHub Actions for webgenr

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Running build...
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Build webgenr
        run: cargo install --verbose --path .

      - name: Build examples
        run: |
         cd examples/nested-files
         webgenr
         cd ../simple-book
         webgenr
         cd ../../
         
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          # Artifact name
          name: github-pages # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: ./examples/nested-files/_website

  deploy:
    name: Deploying build...
    needs: build
    runs-on: ubuntu-latest

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    # Deploy to the github-pages environment
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
         
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        

