name: GitHub Actions for webgenr

on:
  push:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Running build...

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Dump stuff
      run: |
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH
        echo $PATH
        echo $GITHUB_PATH
    - name: Build
      run: cargo install --verbose --path .
    - name: Build examples
      run: |
       cd examples/nested-files
       webgenr
       cd ../simple-book
       webgenr
    - name: Deploy
      run: echo "TODO - deploy examples to gitlab"
